"""Pydantic schemas for the Reflection Engine."""

from pydantic import BaseModel, ConfigDict, Field


class ReflectionRecord(BaseModel):
    """Self-reflection record stored for a user."""

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "reflection_id": "reflect_001",
                    "topic": "Conversation Quality",
                    "reflection": "The conversation was productive and goal oriented",
                    "score": 9,
                }
            ]
        }
    )

    reflection_id: str = Field(
        min_length=1,
        description="Unique reflection record identifier",
        examples=["reflect_001"],
    )
    topic: str = Field(
        min_length=1,
        description="Reflection topic or category",
        examples=["Conversation Quality"],
    )
    reflection: str = Field(
        min_length=1,
        description="Self-reflection text generated by Jarvis",
        examples=["The conversation was productive and goal oriented"],
    )
    score: int = Field(
        ge=0,
        le=10,
        description="Reflection quality score from 0 to 10",
        examples=[9],
    )


class ReflectionRecordResponse(BaseModel):
    """Reflection record returned by the API."""

    reflection_id: str
    topic: str
    reflection: str
    score: int

    @classmethod
    def from_record(cls, record: ReflectionRecord) -> "ReflectionRecordResponse":
        """Build an API response from a stored reflection record."""
        return cls(
            reflection_id=record.reflection_id,
            topic=record.topic,
            reflection=record.reflection,
            score=record.score,
        )


class UserReflectionEngineResponse(BaseModel):
    """All reflection records for one user."""

    user_id: str
    reflections: list[ReflectionRecordResponse]
